version: '3'

services:
  web:
    build: ./app
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8080
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8080:8080
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=my_password
#      - POSTGRES_DB=docker_test

volumes:
  postgres_data: